006-AppModernization/Student/Resources/OnPremApp/IaaS2PaaSWeb/PartsUnlimitedWebsite/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using PartsUnlimited.Models;

namespace PartsUnlimited.ViewModels
{
    public class HomeViewModel
    {
        public List<Product> NewProducts { get; set; }
        public List<Product> TopSellingProducts { get; set; }
        public List<CommunityPost> CommunityPosts { get; set; }
    }
}

006-AppModernization/Student/Resources/OnPremApp/IaaS2PaaSWeb/PartsUnlimitedWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web.Mvc;
using PartsUnlimited.Models;
using PartsUnlimited.ViewModels;

namespace PartsUnlimited.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPartsUnlimitedContext _db;
        public int roco_count = 1000;

        public HomeController(IPartsUnlimitedContext context)
        {
            _db = context;
        }

        //
        // GET: /Home/
        public ActionResult Index()
        {
            // Get most popular products
            var topSellingProducts = MemoryCache.Default["topselling"] as List<Product>;
            if (topSellingProducts == null)
            {
                topSellingProducts = GetTopSellingProducts(4);
                MemoryCache.Default.Add("topselling", topSellingProducts, new CacheItemPolicy { AbsoluteExpiration = DateTimeOffset.UtcNow.AddMinutes(10) });
            }

            var newProducts = MemoryCache.Default["newarrivals"] as List<Product>;
            if (newProducts == null)
            {
                newProducts = GetNewProducts(4);
                MemoryCache.Default.Add("newarrivals", newProducts, new CacheItemPolicy { AbsoluteExpiration = DateTimeOffset.UtcNow.AddMinutes(10) });
            }

            var viewModel = new HomeViewModel
            {
                NewProducts = newProducts,
                TopSellingProducts = topSellingProducts,
                CommunityPosts = GetCommunityPosts()
            };

            return View(viewModel);
        }
        
        private List<Product> GetTopSellingProducts(int count)
        {
            // Group the order details by product and return
            // the products with the highest count

            // TODO [EF] We don't query related data as yet, so the OrderByDescending isn't doing anything
            return _db.Products
                .OrderByDescending(a => a.OrderDetails.Count())
                .Take(count)
                .ToList();
        }


public ActionResult Recomendations()
        {
            ViewBag.Message = "Your application description page.";
            //See file /home/Recomendations.cshtml for initial rendering

            // Group the order details by product and return
            // the products the top recomendations for the recomendations page
            
            int count = 0;
            while (count < roco_count
                   ) 
            {
                _db.Products
                    .OrderByDescending(a => a.OrderDetails.Count())
                    .Take(count++)
                    .ToList();
            }


            return View();
        }
        //stubbing in a recomendations action



        private List<Product> GetNewProducts(int count)
        {
            return _db.Products
                .OrderByDescending(a => a.Created)
                .Take(count)
                .ToList();
        }

        private List<CommunityPost> GetCommunityPosts()
        {
            return new List<CommunityPost>{
                new CommunityPost {
                    Content= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus commodo tellus lorem, et bibendum velit sagittis in. Integer nisl augue, cursus id tellus in, sodales porta.",
                    DatePosted = DateTime.Now,
                    Image = "community_1.png",
                    Source = CommunitySource.Facebook
                },
                new CommunityPost {
                    Content= " Donec tincidunt risus in ligula varius, feugiat placerat nisi condimentum. Quisque rutrum eleifend venenatis. Phasellus a hendrerit urna. Cras arcu leo, hendrerit vel mollis nec.",
                    DatePosted = DateTime.Now,
                    Image = "community_2.png",
                    Source = CommunitySource.Facebook
                },
                new CommunityPost {
                    Content= "Aenean vestibulum non lacus non molestie. Curabitur maximus interdum magna, ullamcorper facilisis tellus fermentum eu. Pellentesque iaculis enim ac vestibulum mollis.",
                    DatePosted = DateTime.Now,
                    Image = "community_3.png",
                    Source = CommunitySource.Facebook
                },
                new CommunityPost {
                    Content= "Ut consectetur sed justo vel convallis. Vestibulum quis metus leo. Nulla hendrerit pharetra dui, vel euismod lectus elementum sit amet. Nam dolor turpis, sodales non mi nec.",
                    DatePosted = DateTime.Now,
                    Image = "community_4.png",
                    Source = CommunitySource.Facebook
                }
            };
        }
    }
}

006-AppModernization/Student/Resources/OnPremApp/IaaS2PaaSWeb/PartsUnlimitedWebsite/Controllers/StoreController.cs
using PartsUnlimited.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Caching;
using System.Web.Mvc;
using PartsUnlimited.Utils;
using PartsUnlimited.ViewModels;
using System.Configuration;
using System.Threading;

namespace PartsUnlimited.Controllers
{
    public class StoreController : Controller
    {
        private readonly IPartsUnlimitedContext db;

        public StoreController(IPartsUnlimitedContext context)
        {
            db = context;
            var configdelay = ConfigurationManager.AppSettings["SiteDelayMilliseconds"];
            int delay = 0;
            int.TryParse(configdelay, out delay);

            Thread.Sleep(delay);
        }

        //
        // GET: /Store/
        public ActionResult Index()
        {
            var genres = db.Categories.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public ActionResult Browse(int categoryId)
        {
            // Retrieve Category genre and its Associated associated Products products from database
            var genreModel = db.Categories.Include("Products").Single(g => g.CategoryId == categoryId);

            return View(genreModel);
        }

        public ActionResult Details(int id)
        {

            var productCacheKey = string.Format("product_{0}", id);
            var product = MemoryCache.Default[productCacheKey] as Product;
            if (product == null)
            {
                product = db.Products.Single(a => a.ProductId == id);
                //Remove it from cache if not retrieved in last 10 minutes
                MemoryCache.Default.Add(productCacheKey, product, new CacheItemPolicy { SlidingExpiration = TimeSpan.FromMinutes(10) });
            }
            var viewModel = new ProductViewModel
            {
                Product = product,
                ShowRecommendations = ConfigurationHelpers.GetBool("ShowRecommendations")
            };

            return View(viewModel);
        }

    }
}

006-AppModernization/Student/Resources/OnPremApp/IaaS2PaaSWeb/PartsUnlimitedWebsite/Views/Home/Index.cshtml
@model PartsUnlimited.ViewModels.HomeViewModel

@{
    ViewBag.Title = "Home Page";
}

@section scripts {
    <script>
        $('.carousel').carousel()
    </script>
}

@section prebody {
<div class="hero-display">
    <div id="jumbotron-carousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#jumbotron-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#jumbotron-carousel" data-slide-to="1"></li>
            <li data-target="#jumbotron-carousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active" style="background-image: url('/Images/hero_image1.jpg')">
                <a href="@Url.Action("Browse", "Store", new { categoryId = 5 })" class="carousel-wrapper-link"></a>
                <p>All oil and filters</p>
                <p>50%</p>
                <p>Christmas discount</p>
                <div class="carousel-caption hidden-xs hidden-sm">
                    <a href="@Url.Action("Browse", "Store", new { categoryId = 5 })" class="carousel-link">Shop Now</a>
                </div>
            </div>
            <div class="item" style="background-image: url('/Images/hero_image2.jpg')">
                <a href="@Url.Action("Browse", "Store", new { categoryId = 3 })" class="carousel-wrapper-link"></a>
                <div class="container">
                    <p>New tires</p>
                    <ul>
                        <li>Improved fuel efficiency</li>
                        <li>Superior wet weather breaking</li>
                        <li>Added durability</li>
                    </ul>
                </div>
                <div class="carousel-caption hidden-xs hidden-sm">
                    <a href="@Url.Action("Browse", "Store", new { categoryId = 3 })" class="carousel-link">Shop Now</a>
                </div>
            </div>
            <div class="item" style="background-image: url('/Images/hero_image3.jpg')">
                <a href="@Url.Action("Index", "Store")" class="carousel-wrapper-link"></a>
                <p>Old<span> or </span>new</p>
                <p>Find the parts for you</p>
                <div class="carousel-caption hidden-xs hidden-sm">
                    <a href="@Url.Action("Browse", "Store", new { categoryId = 3 })" class="carousel-link">Shop Now</a>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#jumbotron-carousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#jumbotron-carousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<div class="featured-areas">
    <div class="container">
        <section class="section-alt">
            <div class="row">
                <div class="area-tile col-xs-12 col-sm-3 col-md-3">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="/Images/submenu_image1.jpg" alt="New Season Parts Image" class="hidden-xs" />
                        <div>New Season Parts</div>
                    </a>
                </div>
                <div class="area-tile col-xs-12 col-sm-3 col-md-3">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="/Images/submenu_image2.jpg" alt="How to Guide Image" class="hidden-xs" />
                        <div>How to Guide</div>
                    </a>
                </div>
                <div class="area-tile col-xs-12 col-sm-3 col-md-3">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="/Images/submenu_image3.jpg" alt="Understand Your Engine Image" class="hidden-xs" />
                        <div>Understand Your Engine</div>
                    </a>
                </div>
                <div class="area-tile col-xs-12 col-sm-3 col-md-3">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="/Images/submenu_image4.jpg" alt="Road Trip Tips Image" class="hidden-xs" />
                        <div>Road Trip Tips</div>
                    </a>
                </div>
            </div>
        </section>
    </div>
</div>
}

<!--TODO : Update github link -->
<a href="https://github.com/" class="hidden-xs">
    <img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/c6625ac1f3ee0a12250227cf83ce904423abf351/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png">
</a>
<div id="home-page">
    <section class="section-alt">
        <h2>Arrivals</h2>
        @Html.Partial("_ProductList", Model.NewProducts)
    </section>
    <section class="section-alt">
        <h2>Top Selling</h2>
        @Html.Partial("_ProductList", Model.TopSellingProducts)
    </section>
    <section class="section-alt">
        <h2>Community</h2>
        @Html.Partial("_CommunityList", Model.CommunityPosts)
    </section>
</div>

006-AppModernization/Student/Resources/OnPremApp/IaaS2PaaSWeb/PartsUnlimitedWebsite/Views/Home/Recomendations.cshtml
@model IEnumerable<PartsUnlimited.Models.Product>
@using PartsUnlimited.Utils
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <h1>Parts Unlimited Online Store Recommenations</h1>
    <title>Your Recommentations</title>
    <h2>Your recomendations are:</h2>
    Brembo Brakes
    Tires
</div>

     