010-AzureDevOps/Student/Resources/Application/src/RazorPagesTestSample/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesTestSample.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

010-AzureDevOps/Student/Resources/Application/src/RazorPagesTestSample/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesTestSample.Data;

namespace RazorPagesTestSample.Pages
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext _db;

        public IndexModel(AppDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Message Message { get; set; }

        public IList<Message> Messages { get; private set; }

        [TempData]
        public string MessageAnalysisResult { get; set; }

        #region snippet1
        public async Task OnGetAsync()
        {
            Messages = await _db.GetMessagesAsync();
        }
        #endregion

        public async Task<IActionResult> OnPostAddMessageAsync()
        {
            if (!ModelState.IsValid)
            {
                Messages = await _db.GetMessagesAsync();

                return Page();
            }

            await _db.AddMessageAsync(Message);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAllMessagesAsync()
        {
            await _db.DeleteAllMessagesAsync();

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteMessageAsync(int id)
        {
            await _db.DeleteMessageAsync(id);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAnalyzeMessagesAsync()
        {
            Messages = await _db.GetMessagesAsync();

            if (Messages.Count == 0)
            {
                MessageAnalysisResult = "There are no messages to analyze.";
            }
            else
            {
                var wordCount = 0;

                foreach (var message in Messages)
                {
                    wordCount += message.Text.Split(' ').Length;
                }

                var avgWordCount = Decimal.Divide(wordCount, Messages.Count);
                MessageAnalysisResult = $"The average message length is {avgWordCount:0.##} words.";
            }

            return RedirectToPage();
        }
    }
}

010-AzureDevOps/Student/Resources/Application/src/RazorPagesTestSample/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Message System";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-8">

        <form method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Add a message</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label asp-for="Message.Text"></label>
                        <input asp-for="Message.Text" class="form-control" style="width:70%;margin-bottom:5px">
                        <span asp-validation-for="Message.Text" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" asp-page-handler="AddMessage" class="btn btn-default">Add Message</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

<div class="row">
    <div class="col-md-8">

        <form method="post">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <button type="submit" asp-page-handler="DeleteAllMessages" class="pull-right btn btn-danger">Clear All</button>
                    <h3 class="panel-title" style="line-height:2.1">Messages</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        @foreach (var message in Model.Messages)
                        {
                            <li style="line-height:2.4">
                                <button type="submit" class="btn btn-danger" style="margin-bottom:2px" asp-page-handler="DeleteMessage" asp-route-id="@message.Id">Delete</button>
                                @message.Text
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </form>

    </div>
</div>

<div class="row">
    <div class="col-md-8">

        <form method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Analyze Messages</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <button type="submit" asp-page-handler="AnalyzeMessages" class="btn btn-default">Analyze</button>
                    </div>
                    <div class="form-group">
                        @Model.MessageAnalysisResult
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>